server:
  port: 8080
  servlet:
    register-default-servlet: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeout
      username: root
      password: 123456
  servlet:
    multipart:
      max-file-size: 2MB
mybatis-plus:
#  驼峰命名,AddressBook --->   address_book
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

uploadPath:
  path: "F:/CodeCount/imageCount/"

